# Generated by Django 2.2 on 2020-07-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, verbose_name='评论目标')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
