# Generated by Django 2.2 on 2020-07-31 03:51

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否为导航栏')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常'), (2, '草稿')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('desc', models.CharField(max_length=128, verbose_name='摘要')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', DjangoUeditor.models.UEditorField(blank=True)),
                ('pv', models.PositiveIntegerField(default=1, verbose_name='点击数')),
                ('uv', models.PositiveIntegerField(default=1, verbose_name='用户访问数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
    ]
