# Generated by Django 2.2 on 2020-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200731_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(2, '草稿'), (1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
    ]
